backend:
  name: git-gateway
  repo: csmaller/plv_nuxt
  branch: main # Branch to update (optional; defaults to master)

media_folder: /public/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'home'
    label: 'Home Page'
    folder: 'content/home'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'visit'
    label: 'Visit Page'
    folder: 'content/visit'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Events Page'
    folder: 'content/events'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          default: 'right',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'info'
    label: 'Info'
    folder: 'content/info'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Address Name', name: 'address_name', widget: 'string' }
      - { label: 'Address Number', name: 'address_number', widget: 'string' }
      - { label: 'City,State,Zip', name: 'city_state', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Hours', name: 'body', widget: 'markdown' }
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'tasting_images'
    extension: 'json'
    label: 'Tasting Room Image Slider'
    files:
      - file: 'content/json/tasting.json'
        label: 'Tasting Room Image Slider'
        name: 'tasting_imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Image”, name: image, widget: image }
  - name: 'main_images'
    extension: 'json'
    label: 'Main Page Images'
    files:
      - file: 'content/json/main.json'
        label: 'Main IMages'
        name: 'imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Tasting Image”, name: tasting_image, widget: image }
              - { label: “Wine Image”, name: wine_image, widget: image }
              - { label: “Events Image”, name: events_image, widget: image }
              - {
                  label: “Experiences Image”,
                  name: experience_image,
                  widget: image,
                }
  - name: 'history_images'
    extension: 'json'
    label: 'History Image Slider'
    files:
      - file: 'content/json/history.json'
        label: 'Image Slider'
        name: 'imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Image”, name: image, widget: image }
  - name: 'events_calendar'
    label: 'Events Calendar'
    extension: 'json'

    files:
      - file: 'content/json/events.json'
        label: 'Events'
        name: 'eventList'
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - { name: title }
              - { label: 'UUID', name: 'uuid', widget: uuid }
              - { name: date, widget: datetime }
              - { name: payment_link }
              - { label: 'Event Details', name: 'body', widget: 'markdown' }
