backend:
  name: git-gateway
  repo: csmaller/plv_nuxt
  branch: main # Branch to update (optional; defaults to master)

media_folder: /public/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'home'
    label: 'Home'
    folder: 'content/home'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Events'
    folder: 'content/events'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'visit'
    label: 'Visit'
    folder: 'content/visit'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Position',
          name: 'image_position',
          widget: 'select',
          options: ['left', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'images'
    extension: 'json'
    label: 'Image Slider'
    files:
      - file: 'public/json/images.json'
        label: 'Image Slider'
        name: 'imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Image”, name: image, widget: image }
  - name: 'events'
    label: 'Events'
    extension: 'json'

    files:
      - file: 'public/json/events.json'
        label: 'Events'
        name: 'eventList'
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - { name: title }
              - { name: date, widget: date }
              - { name: description }
              - { name: payment_link }
